name: python-testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.6'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "lab=11/requirements.txt"
        
    - name: Run tests
      run: |
        pytest "lab=11/tests.py" -v
        pytest "lab=11/tests.py" --junitxml="lab=11/report.xml"
        cat "lab=11/report.xml"