name: python-testing

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.6'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r "lab=11/requirements.txt"
        pip install -r "lab=12/requirements.txt"
        
    - name: Run tests Lab11
      run: |
        pytest "lab=11/tests.py" -v
        pytest "lab=11/tests.py" --junitxml="lab=11/report.xml"
        cat "lab=11/report.xml"

    - name: Run tests Lab12
      run: |
        uvicorn "lab=12.main:app" --host 0.0.0.0 --port 8000 & 
        sleep 5 
        pytest "lab=12/api_tests.py" -v 
        pytest "lab=12/api_tests.py" --junitxml="lab=12/report.xml"
        cat "lab=12/report.xml"